-- ============================================================
-- Chill Point — Supabase Database Schema
-- Run this in your Supabase SQL Editor
-- ============================================================

-- ADMIN CONFIG TABLE
create table if not exists admin_config (
  id text primary key,
  value text not null,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- CATEGORIES TABLE
create table if not exists categories (
  id text primary key,
  label text not null,
  emoji text not null,
  color text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- MENU ITEMS TABLE
create table if not exists menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price integer not null,
  is_available boolean default true,
  is_popular boolean default false,
  is_veg boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- REVIEWS TABLE
create table if not exists reviews (
  id bigint generated by default as identity primary key,
  name text not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security
alter table admin_config enable row level security;
alter table categories enable row level security;
alter table menu_items enable row level security;
alter table reviews enable row level security;

-- Allow public read/write on admin_config (since no central Auth system is configured yet)
create policy "Public can read admin config" on admin_config for select using (true);
create policy "Public can update admin config" on admin_config for update using (true);
create policy "Public can insert admin config" on admin_config for insert with check (true);

-- Allow public read/write on categories 
create policy "Public can read categories" on categories for select using (true);
create policy "Public can insert categories" on categories for insert with check (true);
create policy "Public can update categories" on categories for update using (true);

-- Allow public read/write on menu_items
create policy "Public can read menu items" on menu_items for select using (true);
create policy "Public can insert menu items" on menu_items for insert with check (true);
create policy "Public can update menu items" on menu_items for update using (true);
create policy "Public can delete menu items" on menu_items for delete using (true);

-- Allow public read/write on reviews
create policy "Public can insert reviews" on reviews for insert with check (true);
create policy "Public can read reviews" on reviews for select using (true);

-- ============================================================
-- SEED DATA 
-- ============================================================

-- Initial password
insert into admin_config (id, value) values ('admin_password', 'chillpoint2024') on conflict do nothing;

-- Default Categories
insert into categories (id, label, emoji, color) values
  ('chaat', 'Chaat', '🍛', 'from-orange-400 to-red-500'),
  ('sandwich', 'Sandwich', '🥪', 'from-yellow-400 to-orange-400'),
  ('pizza', 'Pizza', '🍕', 'from-red-400 to-rose-500'),
  ('ice_slush', 'Ice Slush', '🧊', 'from-blue-400 to-cyan-400'),
  ('puff', 'Puff', '🥐', 'from-amber-400 to-yellow-400'),
  ('maggi', 'Maggi', '🍜', 'from-yellow-500 to-amber-500'),
  ('fries', 'Fries', '🍟', 'from-yellow-400 to-orange-500')
on conflict do nothing;

insert into menu_items (name, category, price, is_available, is_popular, is_veg) values
  -- CHAAT
  ('Pani Puri', 'chaat', 20, true, true, true),
  ('Rava Pani Puri', 'chaat', 30, true, false, true),
  ('Masala Puri', 'chaat', 30, true, true, true),
  ('Sev Puri', 'chaat', 40, true, false, true),
  ('Bhel', 'chaat', 40, true, false, true),
  ('Chutney Puri', 'chaat', 40, true, false, true),
  ('Dahi Puri', 'chaat', 50, true, true, true),
  ('Cheese Masala Puri', 'chaat', 50, true, false, true),
  ('Cheese Sev Puri', 'chaat', 70, true, false, true),
  ('Cheese Dahi Puri', 'chaat', 70, true, false, true),

  -- SANDWICH
  ('Bread Butter Jam', 'sandwich', 50, true, false, true),
  ('Bread Butter Chocolate', 'sandwich', 50, true, false, true),
  ('Veg Sandwich', 'sandwich', 60, true, false, true),
  ('Veg Cheese Sandwich', 'sandwich', 100, true, true, true),
  ('Veg Grill Sandwich', 'sandwich', 100, true, true, true),
  ('Veg Cheese Grill', 'sandwich', 110, true, false, true),
  ('Panini Sandwich', 'sandwich', 140, true, true, true),

  -- ICE SLUSH
  ('Orange', 'ice_slush', 30, true, false, true),
  ('Blue Berry', 'ice_slush', 30, true, false, true),
  ('Rose', 'ice_slush', 30, true, false, true),
  ('Kala Khatta', 'ice_slush', 30, true, true, true),
  ('Strawberry', 'ice_slush', 30, true, false, true),
  ('Black Current', 'ice_slush', 30, true, false, true),
  ('Lime', 'ice_slush', 30, true, false, true),
  ('Cola', 'ice_slush', 30, true, false, true),
  ('Mint', 'ice_slush', 30, true, false, true),
  ('Pineapple', 'ice_slush', 30, true, false, true),
  ('Raw Mango', 'ice_slush', 30, true, true, true),

  -- PIZZA
  ('Margherita', 'pizza', 110, true, false, true),
  ('Cheesy Heaven', 'pizza', 150, true, true, true),
  ('Exotic Cheesy Italian', 'pizza', 150, true, false, true),
  ('Mexican', 'pizza', 160, true, false, true),
  ('Tandoori Paneer', 'pizza', 160, true, true, true),

  -- PUFF
  ('Butter Puff', 'puff', 20, true, false, true),
  ('Masala Puff', 'puff', 35, true, false, true),
  ('Cheese Butter Puff', 'puff', 40, true, true, true),

  -- MAGGI
  ('Classic Maggi', 'maggi', 50, true, false, true),
  ('Cheese Maggi', 'maggi', 70, true, true, true),
  ('Vegetable Maggi', 'maggi', 70, true, false, true),

  -- FRIES
  ('Salted Fries', 'fries', 60, true, false, true),
  ('Peri Peri Fries', 'fries', 70, true, true, true),
  ('Extra Cheese', 'fries', 30, true, false, true);

-- Sample reviews
insert into reviews (name, rating, comment) values
  ('Priya Shah', 5, 'Best pani puri in Vadodara! The taste is just like home. Come here every week without fail.'),
  ('Rohan Patel', 5, 'The Cheese Maggi and Peri Peri Fries are absolutely divine. Super affordable and hygienic!'),
  ('Meera Desai', 4, 'Love the ice slush flavors, especially Kala Khatta. Great hangout spot in evenings.'),
  ('Arjun Mehta', 5, 'Cheesy Heaven pizza at just ₹150 is a steal! The Panini Sandwich is also amazing. Must visit!');
